### PR TITLE
Allowing PHP8

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @freekmurze 

I've allowed PHP8 and upgraded one dev dependency to get it working. Tests run through on PHP8.0.0.

Cheers,
Peter

### CODE REVIEW

**Comment by freekmurze** [comment]
I don't see any jobs regarding PHP 8 here yet.

**Comment by freekmurze** [comment]
That's better, now get them all green 🙂

**Comment by spekulatius** [comment]
Little confused here: I've just tried to identify the issue by finding the place where this is called (line is 0 or "n/a" isn't overly helpful on the first look). 

The method with parameters `prepare(string $query, array $options = [])` doesn't exist in the code or dependencies. 

But it is described here: https://www.php.net/manual/en/pdo.prepare.php - notably PHP8 isn't mentioned in the versions on top. Wonder why? I guess like the missing second parameter is handled more strict now.

Not sure what to make from this really. I'll look at it with fresh eyes in the morning

**Comment by spekulatius** [comment]
Looks like dbal is pretty low with v2.3. I could try to pull up it up to 3 or even the current dev-master by adding it to the dependencies. But they all have the same definition of the method in question as far as I remember from my quick look... Going to check it tomorrow unless you got an idea :+1:

**Comment by spekulatius** [comment]
Hey @freekmurze 

After noticing dbal v2.3 in the logs of the failed build I've enforced it to at least 3.0 - with this it's all green :+1: Not sure if there is anything else to look at?

Cheers,
Peter

**Comment by freekmurze** [comment]
Looking good! Thanks!

**Comment by spekulatius** [comment]
No worries, happy to help out!

**Pull request merged**
